config/routes.rb
Rails.application.routes.draw do
  root 'nest#index'

  devise_scope :user do
    devise_for :users, controllers: {
      sessions: 'devise/sessions',
      registrations: 'devise/registrations',
      passwords: 'devise/passwords',
      confirmations: 'devise/confirmations',
      unlocks: 'devise/unlocks'
    }, via: [:get, :post, :delete]
    as :user do
      get 'login' => 'devise/sessions#new'
      get 'sign_up' => 'devise/registrations#new'
      get 'log_out' => 'devise/sessions#destroy'
      resources :users
    end
  end

  get 'about'   =>  'nest#about'
  get 'blog' =>  'posts#index'
  scope '/blog' do
    get 'drafts' => 'posts#drafts'
    resources :posts do
      resources :comments, only: [:index, :create, :edit, :update]
      get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
    end
    resources :tags
  end
  get 'clients/list' =>  'clients#list'
  resources 'clients'
  #resources :comments, only: [:index, :create, :edit, :update]
  #get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get 'contact'	=>  'contacts#new'
  resources 'contacts', only: [ :new, :create ]
  post 'csp_reports' =>  'nest#csp_reports'
  get 'portfolio' => 'nest#portfolio'
  get 'projects/list' =>  'projects#list'
  resources 'projects'
  scope '/previous' do
    resources 'jobs'
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_tree order: "created_at ASC"
  belongs_to :user, foreign_key: "user_id", optional: true
  belongs_to :post, foreign_key: "post_id"

  validates :body, presence: true
  validates :post_id, presence: true

  def author
    if self.user_id.present?
      return User.find(self.user_id).name
    else
      return "Anonymous"
    end
  end
end

app/controllers/comments_controller.rb
require 'recaptcha.rb'
class CommentsController < ApplicationController
  before_action :find_post
  before_action :correct_user, only: [:edit, :update]

  def index
    @comments = Comment.hash_tree
  end

  def new
    @comment = Comment.new(parent_id: params[:parent_id], post_id: @post.id)
    @comment.user_id = current_user.id unless !user_signed_in?
  end

  def create
    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)
    else
      @comment = Comment.new(comment_params)
    end

    if verify_recaptcha(model: @comment)
      user_id = current_user.id unless !user_signed_in?
      post_id = @post.id

      if @comment.update(user_id: user_id, post_id: post_id)
        flash[:success] =  "Your comment was added successfully!"
        Notification.new_comment_admin_notification(@comment).deliver
        redirect_to @post
      else
        flash.now[:error] = "Unable to post comment."
        render :new
      end
    else
      flash.now[:error] = @comment.errors.messages[:base].first
      render :new
    end
  end

  def edit
  end

  def update
    if verify_recaptcha(model: @comment)
      if @comment.update(comment_params)
        flash[:success] =  "Your comment was updated successfully!"
        redirect_to post_path(@post)
      else
        flash.now[:error] = "Unable to update comment."
        render :edit
      end
    else
      flash.now[:error] = @comment.errors.messages[:base].first
      render :edit
    end
  end


  private

  def comment_params
    params.require(:comment).permit(
      :author,
      :body,
      :user_id,
      :post_id,
      :parent_id
    )
  end

  def find_post
    @post = Post.friendly.find(params[:post_id])
  end

  def correct_user
    @comment = Comment.find(params[:id])

    unless admin_is_logged_in? || current_user_id?(@comment.user_id)
      flash[:error] = "Sorry, you do not have access to that part of the site."
      redirect_to(root_url)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) + 
        (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") :nil)
    end.join.html_safe
  end
end

app/views/comments/_comment.html.haml
.comment.rich-text
  %a{ id: comment.id }
  %p.smaller-text
    Posted by
    <strong>#{ link_to_if(!comment.user_id.nil?, comment.author, { controller: "users", action: "show", id: comment.user_id }) }</strong> on&nbsp;
    = comment.created_at.strftime("%e#{comment.created_at.day.ordinal} %B %Y at %H:%M:%S %Z")
    - unless comment.created_at == comment.updated_at
      %em
        = comment.updated_at.strftime("(last modified on %e#{comment.updated_at.day.ordinal} %B %Y at %H:%M:%S %Z)")
    %blockquote
      = raw(comment.body)

  - from_reply_form ||= nil
  - unless from_reply_form
    %ul.divider-list.p-l-0
      %li
        = link_to "reply", post_new_comment_path(@post, comment.id)
      - if admin_is_logged_in? || current_user_id?(comment.user_id)
        %li
          = link_to "edit", edit_post_comment_path(@post, comment)

app/views/comments/_form.html.haml
- provide(:quill_editor, true)

= form_for [@post, @comment] do |f|
  = f.hidden_field :parent_id
  .general-form.container-fluid
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-3.col-xs-2
        = f.label :author, "Posting as"
      .col-lg-4.col-md-4.col-sm-9.col-xs-10.display-inline
        %strong
          = @comment.author
        - unless current_user
          (#{ link_to "Log In", login_path, class: "smaller-text" unless current_user } |&nbsp;
          #{ link_to "Sign Up", sign_up_path, class: "smaller-text" })
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :body, "Comment"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.hidden_field :body, class: 'rich-text-content'
        - if current_user
          #editor-container{ style: 'height: 30rem; width: 100%;'}
            = raw(@comment.body)
        - else
          #editor-container-strict{ style: 'height: 30rem; width: 100%;'}
            = raw(@comment.body)
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        .small-centre
          = recaptcha_tags
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.button "Submit", class: "button"

app/views/comments/edit.html.haml
- provide(:title, "Edit Comment")
= render "layouts/blog_login_logout"
%h1
  Edit Comment

- if @comment.parent
  = render "comment", comment: @comment.parent, from_reply_form: true

= render partial: "form"

%ul.divider-list.p-l-0
  %li
    = link_to "Back To Blog Post", post_path(@post)

app/views/comments/index.html.haml
= link_to "Post a comment", new_comment_path

= comments_tree_for @comments

app/views/comments/new.html.haml
- provide(:title, "New Comment")
= render partial: "layouts/blog_login_logout"
%article
  %h1
    New Comment

- if @comment.parent
  = render partial: "comment", locals: { comment: @comment.parent }, from_reply_form: true
- else
  = render partial: 'posts/post', locals: { post: @post }

= render partial: "comments/form"

%ul.divider-list.p-l-0
  %li
    = link_to "Back To Blog Post", post_path(@post)