config/routes.rb
Rails.application.routes.draw do
  root 'nest#index'

  devise_scope :user do
    devise_for :users, controllers: {
      sessions: 'devise/sessions',
      registrations: 'devise/registrations',
      passwords: 'devise/passwords',
      confirmations: 'devise/confirmations',
      unlocks: 'devise/unlocks'
    }, via: [:get, :post, :delete]
    as :user do
      get 'login' => 'devise/sessions#new'
      get 'sign_up' => 'devise/registrations#new'
      get 'log_out' => 'devise/sessions#destroy'
      resources :users
    end
  end

  get 'about'   =>  'nest#about'
  get 'blog' =>  'posts#index'
  scope '/blog' do
    get 'drafts' => 'posts#drafts'
    resources :posts do
      resources :comments, only: [:index, :create, :edit, :update]
      get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
    end
    resources :tags
  end
  get 'clients/list' =>  'clients#list'
  resources 'clients'
  #resources :comments, only: [:index, :create, :edit, :update]
  #get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get 'contact'	=>  'contacts#new'
  resources 'contacts', only: [ :new, :create ]
  post 'csp_reports' =>  'nest#csp_reports'
  get 'portfolio' => 'nest#portfolio'
  get 'projects/list' =>  'projects#list'
  resources 'projects'
  scope '/previous' do
    resources 'jobs'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  has_many :comments
  

  validates :name,    presence: true,
        length: {maximum: 50},
        uniqueness: {case_sensitive: false}
  validate :not_a_banned_name
  validates :email,   presence: true,
        length: {maximum: 255},
        uniqueness: {case_sensitive: false}
  validates :password,   presence: true,
        length: {minimum: 6},
        allow_nil: true
  
  BANNED_NAMES = ['anonymous', 'anon', 'webmaster', 'admin']


  def locked?
    return true unless self.locked_at == nil
  end

  def admin?
    return true if self.admin == true
  end

  private

  def not_a_banned_name
    if BANNED_NAMES.include?(name)
      errors.add(:name, 'must be a valid name')
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
   def edit
     super
   end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
   def destroy
     super
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
   def cancel
     super
   end
   
  protected

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  prepend_before_action :require_no_authentication, only: [:cancel ]
  before_action :redirect_to_login, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.order(:id).paginate(page: params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User was created successfully."
      redirect_to user_path(@user)
    else
      flash.now[:error] = "An error has prevented this account from being saved."
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      flash.now[:error] = "Unable to update profile."
      render :edit
    end
  end


  def admin_new
    @user = User.new
  end

  def admin_create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User was created successfully."
      redirect_to user_path(@user)
    else
      flash.now[:error] = "An error has prevented this account from being saved."
      render :new
    end
  end

  def destroy
    if current_user_or_admin?(@user)
      @user.destroy
      flash[:success] = "User deleted."
      redirect_to users_url
    else
      flash[:error] = "Sorry, you do not have access to that part of the site."
      render :show, status: :forbidden
    end
  end


  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :bio
    )
  end

  def correct_user
    find_user
    unless current_user.admin? || current_user?(@user)
      flash[:error] = "Sorry, you do not have access to that part of the site."
      redirect_to root_url
    end
  end
end

app/views/users/_admin_form.html.haml
= form_for(@user, :url => '/users/admin_create') do |f|
  .general_form.container-fluid
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :name, "Name:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.text_field :name
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :email, "Email Address:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.email_field :email
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :password, "Password:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.password_field :password
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :password_confirmation, "Confirm Password:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.password_field :password_confirmation
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :bio, "Bio:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.text_area :bio, rows: 10
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.button "Submit", class: "button"

app/views/users/_edit_form.html.haml
= form_for(@user) do |f|
  .general-form.container-fluid
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :name, "Name:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.text_field :name
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :email, "Email Address:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.email_field :email
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :password, "Password:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        - if @user == current_user
          = link_to "Reset password", edit_password_path(@user)
        - else
          = link_to "Reset password", new_password_path(@user)
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :bio, "Bio:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.text_area :bio, rows: 10
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.button "Submit", class: "button"

app/views/users/_new_form.html.haml
= form_for(@user) do |f|
  .general-form.container-fluid
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :name, "Name:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.text_field :name
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :email, "Email Address:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.email_field :email
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :password, "Password:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.password_field :password
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :password_confirmation, "Confirm Password:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.password_field :password_confirmation
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :bio, "Bio:"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.text_area :bio, rows: 10
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.button "Submit", class: "button"

app/views/users/admin_new.html.haml
- provide(:title, "New User")
= render "layouts/blog_login_logout"
%h1
  New User

= render partial: "admin_form"

%ul.divider-list.p-l-0
  %li
    = link_to "Back to All Users", users_path

app/views/users/edit.html.haml
- provide(:title, "Update User")
= render partial: "layouts/blog_login_logout"
%h1
  Update User

= render partial: "users/edit_form"

%ul.divider-list.p-l-0
  %li
    = link_to "Back to All Users", users_path
  - if admin_is_logged_in?
    %li
      = link_to "Delete Account", @user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/index.html.haml
- provide(:title, 'All Users')
= render partial: "layouts/blog_login_logout"
%h1
  All Users

= will_paginate

%table
  %tr
    %th
      ID
    %th
      Name
    %th
      Bio
  - @users.each do |user|
    - unless user.locked?
      %tr
        %td
          = user.id
        %td
          = link_to user.name, user
        %td
          = user.bio.to_s.truncate(50)
        %td
          - if admin_is_logged_in? || current_user?(user)
            = link_to "Edit", edit_user_path(user)
        %td
          - if admin_is_logged_in?
            = link_to "Delete", user, method: :delete,
              data: { cofirm: "Are you sure?" }  unless current_user?(user)

= will_paginate

app/views/users/new.html.haml
- provide(:title, "New User")
= render partial: "layouts/blog_login_logout"
%h1
  New User

= render partial: "users/new_form"

%ul.divider-list.p-l-0
  %li
    = link_to "Back to All Users", users_path

app/views/users/show.html.haml
- provide(:title, @user.name)
= render "layouts/blog_login_logout"
%h1
  = @user.name
.row
  .col-lg-2.col-md-2.col-sm-12.col-xs-12
    %strong
      ID:
  .col-lg-8.col-md-9.col-sm-12.col-xs-12
    = @user.id
.row
  .col-lg-2.col-md-2.col-sm-12.col-xs-12
    %strong
      Name:
  .col-lg-8.col-md-9.col-sm-12.col-xs-12
    = @user.name
- if admin_is_logged_in? || current_user?(@user)
  .row
    .col-lg-2.col-md-2.col-sm-12.col-xs-12
      %strong
        Email Address:
    .col-lg-8.col-md-9.col-sm-12.col-xs-12
      = @user.email
.row
  .col-lg-2.col-md-2.col-sm-12.col-xs-12
    %strong
      Bio:
  .col-lg-8.col-md-9.col-sm-12.col-xs-12
    = markdown(@user.bio) if @user.bio.present?
.row
  .col-lg-2.col-md-2.col-sm-12.col-xs-12
    %strong
      Previous comments:
  .col-lg-8.col-md-9.col-sm-12.col-xs-12
    %ul
      - @user.comments.each do |comment|
        %li
          %strong
            = link_to "Posted under \"#{comment.post.title}\"",
              { controller: "posts", action: "show", id: comment.post_id, anchor: comment.id }
          .comment.rich-text
            = truncate_body(comment.body, length = 25)

%ul.divider-list.p-l-0
  %li
    = link_to "Back to All Users", users_path
  - if user_signed_in?
    - if admin_is_logged_in? && current_user != @user
      %li
        = link_to "Update Account", edit_user_path(@user)
      %li
        = link_to "Delete Account", @user, method: :delete, data: { confirm: 'Are you sure?' }
    - elsif current_user?(@user)
      %li
        = link_to "Update Account", edit_user_registration_path