config/routes.rb
Rails.application.routes.draw do
  root 'nest#index'

  devise_scope :user do
    devise_for :users, controllers: {
      sessions: 'devise/sessions',
      registrations: 'devise/registrations',
      passwords: 'devise/passwords',
      confirmations: 'devise/confirmations',
      unlocks: 'devise/unlocks'
    }, via: [:get, :post, :delete]
    as :user do
      get 'login' => 'devise/sessions#new'
      get 'sign_up' => 'devise/registrations#new'
      get 'log_out' => 'devise/sessions#destroy'
      resources :users
    end
  end

  get 'about'   =>  'nest#about'
  get 'blog' =>  'posts#index'
  scope '/blog' do
    get 'drafts' => 'posts#drafts'
    resources :posts do
      resources :comments, only: [:index, :create, :edit, :update]
      get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
    end
    resources :tags
  end
  get 'clients/list' =>  'clients#list'
  resources 'clients'
  #resources :comments, only: [:index, :create, :edit, :update]
  #get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get 'contact'	=>  'contacts#new'
  resources 'contacts', only: [ :new, :create ]
  post 'csp_reports' =>  'nest#csp_reports'
  get 'portfolio' => 'nest#portfolio'
  get 'projects/list' =>  'projects#list'
  resources 'projects'
  scope '/previous' do
    resources 'jobs'
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  before_save :publish
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged]

  has_many :post_tags, dependent: :destroy
  has_many :tags, -> { distinct }, through: :post_tags
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 75 }, uniqueness: true
  validates :body, length: { maximum: 20000 }
  validates :rich_text_body, presence: true,
    length: { minimum: 14 }, uniqueness: true
#	validates :post_tags, presence: true, associated: true

  #validate :rich_text_body_is_unique

  scope :drafts, proc { where(draft: true) }
  scope :published, proc { where(draft: false).order("published_at DESC") }

  def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  end

  def publish
    if (self.draft == false) && (self.published_at == nil)
      self.published_at = Time.now
    end
  end

  def published_format
    published_at.strftime(
      "Published %e#{published_at.day.ordinal} %B %Y at %I:%M%P %Z"
    ) if published_at.present?
  end

  def updated_format
    updated_at.strftime(
      "(Last Updated %e#{updated_at.day.ordinal} %B %Y at %I:%M%P %Z)"
    ) if published_at.present? && (published_at.to_date != updated_at.to_date)
  end

  def self.post_date
    date = {}

    Post.published.group_by { |post| post.published_at.year }
      .sort.reverse.each do |year, e|
        date[year] = e.group_by { |post| post.published_at.month }
      end
    return date
  end

  def tag_names
    tags.map(&:name)
  end

=begin
  def rich_text_body_is_unique
    current_rich_text_body =
      ActionText::Content.new(rich_text_body.try(:body).try(:to_html))

    if ActionText::RichText.where(body: current_rich_text_body)
      .where('id != ?', id).any?
      errors[:rich_text_body] << "must be unique"
    end
  end
=end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :admin_user_404, except: [:index, :show]
  before_action :friendly_finder, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_draft, only: [:show]

  def index
    @posts = Post.published.paginate(page: params[:page]).per_page(10)
  end

  def drafts
    @posts = Post.drafts.paginate(page: params[:page]).per_page(10)
  end

  def show
    @post = Post.includes(:tags).includes(:comments).friendly.find(params[:id])
    if @post.draft == true
      admin_user_404
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      Tag.tag_relationship(@post)
      flash[:success] = "Post was created successfully."
      redirect_to @post
    else
      flash.now[:error] = "An error has prevented this post from being saved."
      render :new
    end
  end

  def edit
    @post = Post.includes(:tags).friendly.find(params[:id])
  end

  def update
    @post = Post.includes(:tags).friendly.find(params[:id])
    if @post.update(post_params)
      Tag.tag_relationship(@post)
      flash[:success] = "Post updated."
      redirect_to @post
    else
      flash.now[:error] = "Unable to update post."
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted."
    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post)
      .permit(
        :title,
        :body,
        :rich_text_body,
        :draft,
        :published_at,
        :tag_list
      )
  end

  def friendly_finder
    @post = Post.includes(:tags).includes(:comments).friendly.find(params[:id])
  end

  def redirect_if_draft
    friendly_finder
    unless @post.draft == false || (current_user && current_user.admin?) 
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/helpers/posts_helper.rb
require "coderay"
require "redcarpet"

module PostsHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      language ||= :plaintext
      CodeRay.scan(code, language).div(css: :class)
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new()

    options = {
      filter_html: false,
      hard_wrap: true,
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      tables: true,
      no_styles: false,
      tokens: true
    }

    # TODO - Not sure what this line does so may completely remove later on if
    # nothing breaks
    # style = CodeRay::Encoders[:html]::CSS.new(:default).stylesheet

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    return markdown_to_html.render(text).html_safe
  end

  def truncate_body(rich_text_body, length = 590)
    if rich_text_body.present?
      Nokogiri::HTML(
        rich_text_body.truncate(length+3)
      ).to_html.strip.html_safe
    end
  end
end

app/views/posts/_blog_archives.html.haml
-#- Post.post_date.each do |year, month_hash|
  -#.blog_archive_year
    -#= link_to year, "#", id: "accordion"
      -#.blog_archive_year_list.accordion-inner
        -#- month_hash.each do |month, post_record|
          -#.blog_archive_month
            -#-#= link_to Date::MONTHNAMES[month], "#"
            -#.blog_archive_month_list.accordion-inner
              -#- post_record.each do |post|
                -#= link_to "#{post.published_at.strftime("%d/%m/%y")} - #{post.title}", post_path(post)

-#- unless !admin_is_logged_in?
  -#.blog_archive_draft
    -#%a{ href: "#" }
      -#Draft
  -#.blog_archive_draft_list
    -#- Post.all.where(draft: true).order("published_at DESC").each do |draft_post|
      -#= link_to "#{draft_post.created_at.strftime("%d/%m/%y")} - #{draft_post.title}", post_path(draft_post)

app/views/posts/_form.html.haml
- provide(:quill_editor, true)

= form_for @post do |f|
  .general-form.container-fluid
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :title, "Title"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.text_field :title
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :body, "Body"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.hidden_field :rich_text_body, class: 'rich-text-content'
        #editor-container{ style: 'height: 30rem; width: 100%;'}
          = raw(@post.rich_text_body)

    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
        = f.label :tag_list, "Tags"
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.text_field :tag_list
    %fieldset.row
      .col-md-2.col-sm-2.col-xs-2
        = f.label :draft, "Draft?"
      .col-md-4.col-sm-7.col-xs-7
        = f.check_box :draft
    %fieldset.row
      .col-lg-2.col-md-2.col-sm-12.col-xs-12
      .col-lg-8.col-md-9.col-sm-12.col-xs-12
        = f.button "Submit", class: "button"

app/views/posts/_post.html.haml
%article.rich-text
  %h2.blog-index-titles
    = link_to post.title, post
    &nbsp;
    %small.smaller-text
      %em
        (#{ pluralize(post.comments.count, "comment") })

  %em
    = post.published_format

  .p-t-1r
    = truncate_body(post.rich_text_body)
    = link_to "[Read more...]", post

  %br
  - if admin_is_logged_in?
    %ul.divider-list.p-l-0
      %li
        = link_to "Edit Post", edit_post_path(post)
      %li
        = link_to "Delete Post", post, method: :delete, data: { cofirm: "Are you sure? This cannot be undone!"}

app/views/posts/_social_media.html.haml
%section.skin.skin_birman
  #share.social-likes.social-likes_visible{ "data-url": request.url,
    "data-title": "\"#{post.title}\" by Jessica Été (@kohrVid)",
    "data-media": "logo.png" }

    %div{ "data-service": "facebook", title: "Share link on Facebook" }
      Facebook
    %div{ "data-service": "twitter", title: "Share link on Twitter" }
      Twitter
    %div{ "data-service": "linkedin", title: "Share link on LinkedIn" }
      LinkedIn
    %div{ "data-service": "telegram", title: "Share link on Telegram" }
      Telegram
    %div{ "data-service": "pinterest", title: "Share link on Pintrest" }
      Pinterest
    %div{ "data-service": "vkontakte", title: "Share link on Vkontakte" }
      Vkontakte
    %div{ "data-service": "odnoklassniki", title: "Share link on Odnoklassniki" }
      Odnoklassniki
    -#%div{ "data-service": "hacker_news", title: "Share link on Hacker News" }
      -#Hacker News

app/views/posts/drafts.html.haml
- provide(:title, 'Blog | Drafts')
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
= render partial: 'layouts/blog_login_logout'
%h1
  Draft Blog Posts

= will_paginate
- @posts.each do |post|
  = render partial: 'posts/post', locals: { post: post }
= will_paginate

app/views/posts/edit.html.haml
- provide(:title, "Edit Post")
= render partial: "layouts/blog_login_logout"
%h1
  Edit Blog Post

= render partial: "posts/form"

%ul.divider-list
  %li
    = link_to "Back to All Posts", posts_path
  %li
    = link_to "Back to #{@post.title}", post_path(@post)
  - if admin_is_logged_in?
    %li
      = link_to "Delete Post", @post, method: :delete, data: { confirm: "Are you sure? This cannot be undone but saving this as a draft will hide the post instead." }

app/views/posts/index.html.haml
- provide(:title, 'Blog')
= render partial: 'layouts/blog_login_logout'
%h1
  Blog

= will_paginate
- @posts.each do |post|
  = render partial: 'posts/post', locals: { post: post }
= will_paginate

app/views/posts/new.html.haml
- provide(:title, "New Post")
= render partial: "layouts/blog_login_logout"
%h1
  New Post

= render partial: "posts/form"

%ul.divider-list
  %li
    = link_to "Back to All Posts", posts_path

app/views/posts/show.html.haml
- provide(:title, @post.title)
- provide(:blog_post, true)
= render partial: "layouts/blog_login_logout"

%article.rich-text
  %h1.blog-title
    = @post.title
  %p
    %em
      = @post.published_format
      &nbsp;
    %em.smaller-text
      = @post.updated_format

  - unless !@post.draft?
    #error_explanation.alerts
      %h4.alert
        This is a draft
  = raw(@post.rich_text_body)

  %section
    %ul.tags.p-l-0
      - @post.tags.each do |tag|
        %li
          = link_to tag.name, tag

  = render partial: "posts/social_media", locals: { post: @post }

  %ul.divider-list.p-l-0
    %li
      - if @post.draft == false
        = link_to "Back to All Posts", posts_path
      - if (@post.draft == true) && admin_is_logged_in?
        = link_to "Back to All Drafts", drafts_path

    - if admin_is_logged_in?
      %li
        = link_to "Edit Post", edit_post_path(@post)
      %li
        = link_to "Delete Post", @post,
          method: :delete,
          data: { confirm: "Are you sure? This cannot be undone but saving this as a draft will hide the post instead." }

= link_to "Post a comment", post_new_comment_path(@post)

= comments_tree_for @post.comments.hash_tree