config/routes.rb
Rails.application.routes.draw do
  root 'nest#index'

  devise_scope :user do
    devise_for :users, controllers: {
      sessions: 'devise/sessions',
      registrations: 'devise/registrations',
      passwords: 'devise/passwords',
      confirmations: 'devise/confirmations',
      unlocks: 'devise/unlocks'
    }, via: [:get, :post, :delete]
    as :user do
      get 'login' => 'devise/sessions#new'
      get 'sign_up' => 'devise/registrations#new'
      get 'log_out' => 'devise/sessions#destroy'
      resources :users
    end
  end

  get 'about'   =>  'nest#about'
  get 'blog' =>  'posts#index'
  scope '/blog' do
    get 'drafts' => 'posts#drafts'
    resources :posts do
      resources :comments, only: [:index, :create, :edit, :update]
      get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
    end
    resources :tags
  end
  get 'clients/list' =>  'clients#list'
  resources 'clients'
  #resources :comments, only: [:index, :create, :edit, :update]
  #get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get 'contact'	=>  'contacts#new'
  resources 'contacts', only: [ :new, :create ]
  post 'csp_reports' =>  'nest#csp_reports'
  get 'portfolio' => 'nest#portfolio'
  get 'projects/list' =>  'projects#list'
  resources 'projects'
  scope '/previous' do
    resources 'jobs'
  end
end

app/views/layouts/_alerts.html.haml
- if flash.present?
  .alerts
    - flash.each do |key, value|
      %div{ class: key }
        %h4
          = value
        %a.close{ href: "#" }
          &times;
        - if list_current_errors.any?
          The form contains #{ pluralize(list_current_errors.count, "error") }.
          %ul
            - list_current_errors.each do |msg|
              %li
                = msg

app/views/layouts/_blog_login_logout.html.haml
.row
  .col-lg-3.col-lg-offset-9.col-md-3.col-md-offset-9.col-sm-3.col-sm-offset-9.col-xs-4.col-xs-offset-8.right-align.position-relative
    %ul.divider-list.p-l-0
      - if admin_is_logged_in?
        - if (params[:controller] == "users") && (params[:action] != "new")
          %li
            = link_to "New User", new_user_path
        - if (params[:controller] == "posts") && (params[:action] != "new")
          %li
            = link_to "New Post", new_post_path
          - if yield(:title) == "Blog"
            %li
              = link_to "Drafts", drafts_path
          - if yield(:title) == "Blog | Drafts"
            %li
              = link_to "Published Posts", blog_path
        - if (params[:controller] == "tags") && (params[:action] != "new")
          %li
            = link_to "New Tag", new_tag_path
      - if user_signed_in?
        %li
          = link_to "Log Out", log_out_path
      - else !user_signed_in?
        %li
          = link_to "Log In", login_path

app/views/layouts/_head.html.haml
%head
  %meta{ charset: "UTF-8" }
  %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
  %meta{ name: "description", content: "" }
  %meta{ name: "keywords", content: meta_keywords  }
  %meta{ name: "google-site-verification",
    content: "" }
  = csrf_meta_tags
  = csp_meta_tag
  %title
    = content_for?(:title) ? "kohrVid | #{yield(:title)}" : "kohrVid"
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  - if content_for?(:quill_editor)
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  - if content_for?(:blog_post)
    = javascript_pack_tag 'post', 'data-turbolinks-track': 'reload'

  = favicon_link_tag 'favicon.ico'
  %script{ type: "application/ld+json" }
    { "@context" : "https://schema.org", "@type" : "Organization", "name" : "TODO insert description", "url" : "https://www.kohrVid.com", "sameAs" : [ "https://twitter.com/kohrVid", "https://github.com/kohrVid" ] }
  = render partial: "layouts/ie_shim"

app/views/layouts/_ie_shim.html.erb
<!--[if lte IE 8 ]>
  <style>
    body{
      background-color: #f3f3f3 !important;
    }
    .container{
      background-color: #f3f3f3 !important;
    }
    #top-bar{
      backgroud-color: #f3f3f3 !important;
        color: #070715 !important;
      }
  </style>
<![endif]-->

app/views/layouts/_navigation.html.haml
#navbar.col-lg-4.col-md-3.col-sm-4.col-xs-12.position-relative
  %nav{ role: "navigation" }
    .row
      #logo.col-lg-7.col-md-7.col-sm-7.col-xs-12
        = link_to "kohrVid", root_path, title: "back to the nest"
      .p-l-1r.hidden-xs.pull-right.col-lg-pull-0.col-md-pull-0.col-sm-pull-0
        = render partial: "layouts/social_media_buttons"
    #hide-on-scroll
      %ul#menu
        %li
          = link_to "About", about_path
        %li
          =link_to "Portfolio", portfolio_path
        %li
          = link_to "Blog", blog_path
        %li
          = link_to "Contact", contact_path
      .small-centre.hidden-lg.hidden-md.hidden-sm
        = render partial: "layouts/social_media_buttons"
      %footer.hidden-xs
        © MMXXII kohrVid

app/views/layouts/_social_media_buttons.html.haml
%ul.inline-list.p-l-0
  %li
    %span.icon
      = link_to image_tag( "github.png"), "https://github.com/kohrVid", title: "GitHub"
  %li
    %span.icon
      = link_to image_tag( "twitter.png"), "https://twitter.com/intent/follow?screen_name=kohrVid&tw_p=followbutton", title: "Twitter"

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  = render partial: "layouts/head"
  %body
    #wrapper.container-fluid
      .row
        = render partial: "layouts/navigation"
        %main.col-lg-8.col-md-9.col-sm-8.col-xs-12
          <!--[if lte IE 8 ]>
          Sorry, this site doesn't support IE8 or lower. Please upgrade your browser or try switching to Firefox/Chrome/Opera
          <![endif]-->
          %noscript
            This site looks much nicer with JavaScript enabled so please make sure it's switched on in your browser settings if possible.
          = render partial: "layouts/alerts"
          = yield
          -#- unless !(@post||@posts).present?
            -#.blog_archives
              -#= render partial: "posts/blog_archives"

    .container-fluid
      .row
        %footer#small-footer.hidden-lg.hidden-md.hidden-sm.col-xs-12
          %center
            © MMXXII kohrVid